name: "Initialize"
description: ""
inputs:
  node-version:
    required: true
    default: 20
runs:
  using: "composite"
  steps:
    - uses: pnpm/action-setup@v2
      with:
        version: 9.5.x

    - name: Use Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'pnpm'

    - run: cp .env.test .env
      shell: bash
