name: "Backend"

on:
  push:
    branches: [ '**' ]

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        node-version: [ 16, 18 ]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/workflows/actions/setup
        with:
          node-version: ${{ matrix.node-version }}

      - shell: bash
        run: pnpm install
            --include-workspace-root
            --frozen-lockfile
            --filter=backend...

      - name: Lint infra
        shell: bash
        run: node_modules/.bin/nx run backend:lint:js

      - name: Lint & test backend
        shell: bash
        run: node_modules/.bin/nx run backend:test

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        with:
            projectBaseDir: packages/backend
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
