name: "Workers"


on:
  push:
    branches: [ '**' ]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [ 16, 18 ]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/workflows/actions/setup

      - shell: bash
        run: pnpm install
          --include-workspace-root
          --frozen-lockfile
          --filter=workers...
          --filter=webapp-emails...

      - name: Build emails renderer
        shell: bash
        run: node_modules/.bin/nx run webapp-emails:build-vite

      - name: Build
        shell: bash
        run: node_modules/.bin/nx run workers:build

  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [ 16, 18 ]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/workflows/actions/setup

      - shell: bash
        run: pnpm install
            --include-workspace-root
            --frozen-lockfile
            --filter=workers...

      - name: Lint workers
        shell: bash
        run: node_modules/.bin/nx run workers:lint

      - name: Test workers
        shell: bash
        run: node_modules/.bin/nx run workers:test

#      - name: SonarCloud Scan
#        uses: sonarsource/sonarcloud-github-action@master
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
